# Generated by Django 5.2.3 on 2025-06-29 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=10)),
                ('desc', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2025, 6, 29, 17, 16, 57, 792258))),
            ],
        ),
    ]
