# Generated by Django 5.2.3 on 2025-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
